name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?

  - type: dropdown
    id: module
    attributes:
      label: Related module
      options:
        - Help Center
        - Feedback Board
        - Roadmap
        - Changelog
        - Widget
        - Admin Dashboard
        - Portal
        - API
        - Other
